Fix writing of hex files
There's no need to encode the set of digits into UTF-8; we know it's
pure ASCII. Fixes:

File "CCLib/Python/cclib/cchex.py", line 265, in _write
  f.write((":%s%02x\n" % (toHex(bytes), csum)).encode(encoding="UTF-8"))
TypeError: write() argument must be str, not bytes